import React from "react";
import ReactDOM from "react-dom/client";
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReduxProvider } from './provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <ReduxProvider>
        <html lang="en">
          <body className={inter.className}>
              {children}</body>
        </html>
      </ReduxProvider>
    </>
  )
}

export default RootLayout;
